// Banco de Dados Global (CronoMED)
window.bancoDeMaterias = [
    { area: "Clínica Médica", subarea: "Cardiologia", tema: "Hipertensão Arterial Sistêmica", peso_prova: 10, frequencia_prova: 95, score: 36.5, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Cardiologia", tema: "Síndrome Coronariana Aguda", peso_prova: 10, frequencia_prova: 95, score: 36.5, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Cardiologia", tema: "Insuficiência Cardíaca", peso_prova: 10, frequencia_prova: 90, score: 35, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Cardiologia", tema: "Arritmias Cardíacas", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Cardiologia", tema: "Parada Cardiorrespiratória", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Endocrinologia", tema: "Diabetes Mellitus", peso_prova: 10, frequencia_prova: 95, score: 36.5, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Endocrinologia", tema: "Doenças da Tireoide", peso_prova: 9, frequencia_prova: 90, score: 33.3, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Endocrinologia", tema: "Dislipidemia", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Pneumologia", tema: "Pneumonia", peso_prova: 10, frequencia_prova: 95, score: 36.5, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Pneumologia", tema: "Asma", peso_prova: 9, frequencia_prova: 90, score: 33.3, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Pneumologia", tema: "DPOC", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Pneumologia", tema: "Tromboembolismo Pulmonar", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Neurologia", tema: "Acidente Vascular Cerebral", peso_prova: 10, frequencia_prova: 95, score: 36.5, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Neurologia", tema: "Epilepsia", peso_prova: 9, frequencia_prova: 80, score: 31, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Nefrologia", tema: "Lesão Renal Aguda", peso_prova: 10, frequencia_prova: 90, score: 35, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Nefrologia", tema: "Doença Renal Crônica", peso_prova: 10, frequencia_prova: 85, score: 33.5, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Nefrologia", tema: "Distúrbios Hidroeletrolíticos", peso_prova: 10, frequencia_prova: 90, score: 35, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Gastroenterologia", tema: "Hemorragia Digestiva Alta", peso_prova: 10, frequencia_prova: 90, score: 35, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Gastroenterologia", tema: "Doença Hepática Crônica", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Infectologia", tema: "Sepse e Choque Séptico", peso_prova: 10, frequencia_prova: 95, score: 36.5, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Infectologia", tema: "Infecção do Trato Urinário", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Hematologia", tema: "Anemias", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 1 },
    { area: "Cirurgia", subarea: "Trauma", tema: "ATLS e Avaliação Inicial do Trauma", peso_prova: 10, frequencia_prova: 95, score: 36.5, prioridade: 1 },
    { area: "Cirurgia", subarea: "Cirurgia Geral", tema: "Abdome Agudo", peso_prova: 10, frequencia_prova: 95, score: 36.5, prioridade: 1 },
    { area: "Cirurgia", subarea: "Cirurgia Geral", tema: "Apendicite Aguda", peso_prova: 9, frequencia_prova: 90, score: 33.3, prioridade: 1 },
    { area: "Cirurgia", subarea: "Cirurgia Geral", tema: "Colecistite e Colelitíase", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 1 },
    { area: "Pediatria", subarea: "Neonatologia", tema: "Reanimação Neonatal", peso_prova: 10, frequencia_prova: 95, score: 36.5, prioridade: 1 },
    { area: "Pediatria", subarea: "Geral", tema: "Puericultura", peso_prova: 10, frequencia_prova: 95, score: 36.5, prioridade: 1 },
    { area: "Ginecologia e Obstetrícia", subarea: "Obstetrícia", tema: "Doença Hipertensiva da Gestação", peso_prova: 10, frequencia_prova: 95, score: 36.5, prioridade: 1 },
    { area: "Preventiva", subarea: "Saúde Pública", tema: "Princípios do SUS", peso_prova: 10, frequencia_prova: 95, score: 36.5, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Cardiologia", tema: "Síndromes Aórticas Agudas", peso_prova: 9, frequencia_prova: 80, score: 31, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Cardiologia", tema: "Valvopatias", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Endocrinologia", tema: "Obesidade", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Endocrinologia", tema: "Síndrome Metabólica", peso_prova: 8, frequencia_prova: 70, score: 27, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Pneumologia", tema: "Derrame Pleural", peso_prova: 8, frequencia_prova: 70, score: 27, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Neurologia", tema: "Cefaleias", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Nefrologia", tema: "Distúrbios Ácido-Base", peso_prova: 9, frequencia_prova: 80, score: 31, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Gastroenterologia", tema: "Pancreatite Aguda", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Gastroenterologia", tema: "Diarreia Aguda", peso_prova: 8, frequencia_prova: 70, score: 27, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Infectologia", tema: "Endocardite Infecciosa", peso_prova: 9, frequencia_prova: 80, score: 31, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Infectologia", tema: "Pneumonias Atípicas", peso_prova: 8, frequencia_prova: 70, score: 27, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Reumatologia", tema: "Lúpus Eritematoso Sistêmico", peso_prova: 9, frequencia_prova: 80, score: 31, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Reumatologia", tema: "Artrite Reumatoide", peso_prova: 9, frequencia_prova: 80, score: 31, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Psiquiatria", tema: "Depressão", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Psiquiatria", tema: "Transtornos de Ansiedade", peso_prova: 9, frequencia_prova: 80, score: 31, prioridade: 1 },
    { area: "Cirurgia", subarea: "Cirurgia Geral", tema: "Hérnias da Parede Abdominal", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 2 },
    { area: "Cirurgia", subarea: "Cirurgia Geral", tema: "Perfuração de Víscera Oca", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 2 },
    { area: "Cirurgia", subarea: "Vascular", tema: "Trombose Venosa Profunda", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 1 },
    { area: "Cirurgia", subarea: "Vascular", tema: "Tromboembolismo Pulmonar Cirúrgico", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 2 },
    { area: "Cirurgia", subarea: "Urologia", tema: "Litíase Urinária", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 1 },
    { area: "Cirurgia", subarea: "Urologia", tema: "Hiperplasia Prostática Benigna", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 2 },
    { area: "Pediatria", subarea: "Geral", tema: "Infecções Respiratórias Agudas", peso_prova: 10, frequencia_prova: 95, score: 36.5, prioridade: 1 },
    { area: "Pediatria", subarea: "Geral", tema: "Bronquiolite", peso_prova: 9, frequencia_prova: 90, score: 33.3, prioridade: 1 },
    { area: "Pediatria", subarea: "Geral", tema: "Otite Média Aguda", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 1 },
    { area: "Ginecologia e Obstetrícia", subarea: "Obstetrícia", tema: "Trabalho de Parto Prematuro", peso_prova: 10, frequencia_prova: 90, score: 35, prioridade: 1 },
    { area: "Ginecologia e Obstetrícia", subarea: "Ginecologia", tema: "Infecções Sexualmente Transmissíveis", peso_prova: 10, frequencia_prova: 90, score: 35, prioridade: 1 },
    { area: "Preventiva", subarea: "Epidemiologia", tema: "Medidas de Associação e Risco", peso_prova: 10, frequencia_prova: 95, score: 36.5, prioridade: 1 },
    { area: "Preventiva", subarea: "Epidemiologia", tema: "Tipos de Estudo", peso_prova: 10, frequencia_prova: 95, score: 36.5, prioridade: 1 },
    { area: "Clínica Médica", subarea: "Cardiologia", tema: "Pericardite e Miocardite", peso_prova: 7, frequencia_prova: 65, score: 24.5, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Cardiologia", tema: "Doença Arterial Coronariana Crônica", peso_prova: 8, frequencia_prova: 70, score: 26, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Endocrinologia", tema: "Hipoglicemia", peso_prova: 8, frequencia_prova: 70, score: 26, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Endocrinologia", tema: "Doenças da Hipófise", peso_prova: 7, frequencia_prova: 60, score: 23, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Pneumologia", tema: "Doenças Intersticiais Pulmonares", peso_prova: 7, frequencia_prova: 60, score: 23, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Neurologia", tema: "Doença de Parkinson", peso_prova: 7, frequencia_prova: 65, score: 24.5, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Neurologia", tema: "Esclerose Múltipla", peso_prova: 7, frequencia_prova: 60, score: 23, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Nefrologia", tema: "Síndrome Nefrótica", peso_prova: 8, frequencia_prova: 70, score: 26, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Nefrologia", tema: "Síndrome Nefrítica", peso_prova: 8, frequencia_prova: 70, score: 26, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Gastroenterologia", tema: "Doença Inflamatória Intestinal", peso_prova: 8, frequencia_prova: 70, score: 26, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Gastroenterologia", tema: "Doença do Refluxo Gastroesofágico", peso_prova: 7, frequencia_prova: 65, score: 24.5, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Infectologia", tema: "Tuberculose", peso_prova: 9, frequencia_prova: 80, score: 31, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Infectologia", tema: "HIV", peso_prova: 9, frequencia_prova: 80, score: 31, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Hematologia", tema: "Coagulopatias", peso_prova: 7, frequencia_prova: 65, score: 24.5, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Reumatologia", tema: "Espondiloartrites", peso_prova: 7, frequencia_prova: 60, score: 23, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Reumatologia", tema: "Gota", peso_prova: 7, frequencia_prova: 65, score: 24.5, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Psiquiatria", tema: "Transtorno Bipolar", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Psiquiatria", tema: "Esquizofrenia", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 2 },
    { area: "Cirurgia", subarea: "Cirurgia Geral", tema: "Obstrução Intestinal", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 2 },
    { area: "Cirurgia", subarea: "Cirurgia Geral", tema: "Diverticulite", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 2 },
    { area: "Cirurgia", subarea: "Vascular", tema: "Doença Arterial Obstrutiva Periférica", peso_prova: 7, frequencia_prova: 65, score: 24.5, prioridade: 2 },
    { area: "Cirurgia", subarea: "Proctologia", tema: "Hemorroidas", peso_prova: 7, frequencia_prova: 65, score: 24.5, prioridade: 2 },
    { area: "Cirurgia", subarea: "Urologia", tema: "Câncer de Próstata", peso_prova: 7, frequencia_prova: 60, score: 23, prioridade: 3 },
    { area: "Pediatria", subarea: "Geral", tema: "Infecção do Trato Urinário", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 2 },
    { area: "Pediatria", subarea: "Geral", tema: "Doenças Exantemáticas", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 2 },
    { area: "Pediatria", subarea: "Geral", tema: "Anemias na Infância", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 2 },
    { area: "Ginecologia e Obstetrícia", subarea: "Ginecologia", tema: "Doença Inflamatória Pélvica", peso_prova: 9, frequencia_prova: 80, score: 31, prioridade: 2 },
    { area: "Ginecologia e Obstetrícia", subarea: "Ginecologia", tema: "Endometriose", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 2 },
    { area: "Preventiva", subarea: "Epidemiologia", tema: "Rastreamento", peso_prova: 9, frequencia_prova: 90, score: 33.3, prioridade: 2 },
    { area: "Preventiva", subarea: "Saúde Pública", tema: "Atenção Primária à Saúde", peso_prova: 9, frequencia_prova: 90, score: 33.3, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Cardiologia", tema: "Hipertensão Secundária", peso_prova: 7, frequencia_prova: 65, score: 24.5, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Cardiologia", tema: "Cardiomiopatias", peso_prova: 7, frequencia_prova: 60, score: 23, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Endocrinologia", tema: "Doenças da Adrenal (Cushing e Addison)", peso_prova: 7, frequencia_prova: 65, score: 24.5, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Endocrinologia", tema: "Distúrbios do Crescimento", peso_prova: 6, frequencia_prova: 55, score: 21.5, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Pneumologia", tema: "Câncer de Pulmão", peso_prova: 7, frequencia_prova: 65, score: 24.5, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Pneumologia", tema: "Apneia Obstrutiva do Sono", peso_prova: 6, frequencia_prova: 50, score: 20, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Neurologia", tema: "Demências", peso_prova: 7, frequencia_prova: 65, score: 24.5, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Neurologia", tema: "Neuropatias Periféricas", peso_prova: 6, frequencia_prova: 55, score: 21.5, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Nefrologia", tema: "Glomerulonefrites", peso_prova: 7, frequencia_prova: 65, score: 24.5, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Gastroenterologia", tema: "Colelitíase e Complicações", peso_prova: 7, frequencia_prova: 65, score: 24.5, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Gastroenterologia", tema: "Doença Celíaca", peso_prova: 6, frequencia_prova: 55, score: 21.5, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Infectologia", tema: "Leptospirose", peso_prova: 7, frequencia_prova: 60, score: 23, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Infectologia", tema: "Febre Amarela", peso_prova: 6, frequencia_prova: 55, score: 21.5, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Hematologia", tema: "Anemia Hemolítica", peso_prova: 7, frequencia_prova: 60, score: 23, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Reumatologia", tema: "Vasculites", peso_prova: 7, frequencia_prova: 60, score: 23, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Psiquiatria", tema: "Transtornos Alimentares", peso_prova: 6, frequencia_prova: 50, score: 20, prioridade: 3 },
    { area: "Cirurgia", subarea: "Cirurgia Geral", tema: "Infecções Cirúrgicas", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 2 },
    { area: "Cirurgia", subarea: "Cirurgia Geral", tema: "Antibioticoprofilaxia", peso_prova: 7, frequencia_prova: 70, score: 26, prioridade: 2 },
    { area: "Cirurgia", subarea: "Proctologia", tema: "Fissura Anal", peso_prova: 6, frequencia_prova: 55, score: 21.5, prioridade: 3 },
    { area: "Cirurgia", subarea: "Urologia", tema: "Câncer de Bexiga", peso_prova: 6, frequencia_prova: 55, score: 21.5, prioridade: 3 },
    { area: "Cirurgia", subarea: "Vascular", tema: "Insuficiência Venosa Crônica", peso_prova: 6, frequencia_prova: 55, score: 21.5, prioridade: 3 },
    { area: "Pediatria", subarea: "Neonatologia", tema: "Prematuridade", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 2 },
    { area: "Pediatria", subarea: "Neonatologia", tema: "Distúrbios Respiratórios Neonatais", peso_prova: 9, frequencia_prova: 80, score: 31, prioridade: 2 },
    { area: "Pediatria", subarea: "Geral", tema: "Crescimento e Desenvolvimento", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 2 },
    { area: "Pediatria", subarea: "Geral", tema: "Parasitoses Intestinais", peso_prova: 7, frequencia_prova: 60, score: 23, prioridade: 3 },
    { area: "Ginecologia e Obstetrícia", subarea: "Obstetrícia", tema: "Rotura Prematura de Membranas", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 2 },
    { area: "Ginecologia e Obstetrícia", subarea: "Obstetrícia", tema: "Restrição de Crescimento Intrauterino", peso_prova: 9, frequencia_prova: 80, score: 31, prioridade: 2 },
    { area: "Preventiva", subarea: "Saúde Pública", tema: "Estratégia Saúde da Família", peso_prova: 9, frequencia_prova: 90, score: 33.3, prioridade: 2 },
    { area: "Preventiva", subarea: "Epidemiologia", tema: "Sensibilidade e Especificidade", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Cardiologia", tema: "Doenças do Pericárdio", peso_prova: 6, frequencia_prova: 55, score: 21.5, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Cardiologia", tema: "Síncope", peso_prova: 6, frequencia_prova: 50, score: 20, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Endocrinologia", tema: "Hipercalcemia e Hipocalcemia", peso_prova: 6, frequencia_prova: 55, score: 21.5, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Endocrinologia", tema: "Distúrbios da Paratireoide", peso_prova: 5, frequencia_prova: 45, score: 18.5, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Pneumologia", tema: "Bronquiectasias", peso_prova: 6, frequencia_prova: 50, score: 20, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Pneumologia", tema: "Pneumotórax", peso_prova: 7, frequencia_prova: 60, score: 23, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Neurologia", tema: "Síndromes Cerebelares", peso_prova: 5, frequencia_prova: 45, score: 18.5, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Neurologia", tema: "Miopatias", peso_prova: 5, frequencia_prova: 45, score: 18.5, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Nefrologia", tema: "Doença Policística Renal", peso_prova: 5, frequencia_prova: 45, score: 18.5, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Gastroenterologia", tema: "Síndrome do Intestino Irritável", peso_prova: 6, frequencia_prova: 50, score: 20, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Gastroenterologia", tema: "Constipação Crônica", peso_prova: 5, frequencia_prova: 45, score: 18.5, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Infectologia", tema: "Dengue", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Infectologia", tema: "Zika e Chikungunya", peso_prova: 6, frequencia_prova: 55, score: 21.5, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Hematologia", tema: "Leucemias", peso_prova: 7, frequencia_prova: 60, score: 23, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Reumatologia", tema: "Síndrome de Sjögren", peso_prova: 5, frequencia_prova: 45, score: 18.5, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Psiquiatria", tema: "Transtornos de Personalidade", peso_prova: 6, frequencia_prova: 50, score: 20, prioridade: 3 },
    { area: "Cirurgia", subarea: "Cirurgia Geral", tema: "Queimaduras", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 3 },
    { area: "Cirurgia", subarea: "Cirurgia Geral", tema: "Choque no Trauma", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 3 },
    { area: "Cirurgia", subarea: "Proctologia", tema: "Abscesso Anorretal", peso_prova: 6, frequencia_prova: 50, score: 20, prioridade: 3 },
    { area: "Cirurgia", subarea: "Urologia", tema: "Infecção Urinária Complicada", peso_prova: 7, frequencia_prova: 60, score: 23, prioridade: 3 },
    { area: "Cirurgia", subarea: "Vascular", tema: "Aneurisma de Aorta Abdominal", peso_prova: 7, frequencia_prova: 60, score: 23, prioridade: 3 },
    { area: "Pediatria", subarea: "Geral", tema: "Desidratação", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 2 },
    { area: "Pediatria", subarea: "Geral", tema: "Aleitamento Materno", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 3 },
    { area: "Pediatria", subarea: "Neonatologia", tema: "Icterícia Neonatal", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 2 },
    { area: "Ginecologia e Obstetrícia", subarea: "Obstetrícia", tema: "Placenta Prévia", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 2 },
    { area: "Ginecologia e Obstetrícia", subarea: "Obstetrícia", tema: "Descolamento Prematuro de Placenta", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 2 },
    { area: "Preventiva", subarea: "Epidemiologia", tema: "Valor P e Intervalo de Confiança", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 3 },
    { area: "Preventiva", subarea: "Saúde Pública", tema: "Vigilância Epidemiológica", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Cardiologia", tema: "Doença de Chagas (forma cardíaca)", peso_prova: 6, frequencia_prova: 55, score: 21.5, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Cardiologia", tema: "Cardiopatia Congênita no Adulto", peso_prova: 5, frequencia_prova: 45, score: 18.5, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Endocrinologia", tema: "Cetoacidose Diabética", peso_prova: 9, frequencia_prova: 80, score: 31, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Endocrinologia", tema: "Estado Hiperosmolar Hiperglicêmico", peso_prova: 8, frequencia_prova: 70, score: 26, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Pneumologia", tema: "Aspergilose", peso_prova: 5, frequencia_prova: 45, score: 18.5, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Pneumologia", tema: "Doenças Ocupacionais Pulmonares", peso_prova: 5, frequencia_prova: 45, score: 18.5, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Neurologia", tema: "Síndrome de Guillain-Barré", peso_prova: 7, frequencia_prova: 60, score: 23, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Neurologia", tema: "Miastenia Gravis", peso_prova: 7, frequencia_prova: 60, score: 23, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Nefrologia", tema: "Nefropatia Diabética", peso_prova: 8, frequencia_prova: 70, score: 26, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Nefrologia", tema: "Nefrite Lúpica", peso_prova: 7, frequencia_prova: 60, score: 23, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Gastroenterologia", tema: "Hepatites Virais", peso_prova: 9, frequencia_prova: 80, score: 31, prioridade: 2 },
    { area: "Clínica Médica", subarea: "Gastroenterologia", tema: "Colangite e Colestase", peso_prova: 6, frequencia_prova: 55, score: 21.5, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Infectologia", tema: "Malária", peso_prova: 7, frequencia_prova: 60, score: 23, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Infectologia", tema: "Parasitoses Sistêmicas", peso_prova: 5, frequencia_prova: 45, score: 18.5, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Hematologia", tema: "Linfomas", peso_prova: 7, frequencia_prova: 60, score: 23, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Reumatologia", tema: "Polimialgia Reumática", peso_prova: 5, frequencia_prova: 45, score: 18.5, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Psiquiatria", tema: "Abuso de Substâncias", peso_prova: 7, frequencia_prova: 65, score: 24.5, prioridade: 3 },
    { area: "Cirurgia", subarea: "Cirurgia Geral", tema: "Câncer Gástrico", peso_prova: 7, frequencia_prova: 60, score: 23, prioridade: 3 },
    { area: "Cirurgia", subarea: "Cirurgia Geral", tema: "Câncer Colorretal", peso_prova: 8, frequencia_prova: 70, score: 26, prioridade: 2 },
    { area: "Cirurgia", subarea: "Proctologia", tema: "Fístula Anal", peso_prova: 6, frequencia_prova: 55, score: 21.5, prioridade: 3 },
    { area: "Cirurgia", subarea: "Urologia", tema: "Torção Testicular", peso_prova: 8, frequencia_prova: 70, score: 26, prioridade: 2 },
    { area: "Cirurgia", subarea: "Vascular", tema: "Dissecção de Aorta", peso_prova: 8, frequencia_prova: 70, score: 26, prioridade: 2 },
    { area: "Pediatria", subarea: "Geral", tema: "Crises Convulsivas na Infância", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 2 },
    { area: "Pediatria", subarea: "Geral", tema: "Obesidade Infantil", peso_prova: 7, frequencia_prova: 65, score: 24.5, prioridade: 3 },
    { area: "Pediatria", subarea: "Neonatologia", tema: "Sepse Neonatal", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 2 },
    { area: "Ginecologia e Obstetrícia", subarea: "Ginecologia", tema: "Mioma Uterino", peso_prova: 8, frequencia_prova: 75, score: 28.5, prioridade: 2 },
    { area: "Ginecologia e Obstetrícia", subarea: "Ginecologia", tema: "Câncer de Colo do Útero", peso_prova: 9, frequencia_prova: 85, score: 32.5, prioridade: 2 },
    { area: "Preventiva", subarea: "Saúde Pública", tema: "Promoção da Saúde", peso_prova: 7, frequencia_prova: 65, score: 24.5, prioridade: 3 },
    { area: "Preventiva", subarea: "Epidemiologia", tema: "Curvas Epidêmicas", peso_prova: 6, frequencia_prova: 55, score: 21.5, prioridade: 3 },
    { area: "Clínica Médica", subarea: "Cardiologia", tema: "Tumores Cardíacos", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Cardiologia", tema: "Doença de Kawasaki (repercussões cardíacas)", peso_prova: 5, frequencia_prova: 40, score: 17, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Endocrinologia", tema: "Síndromes Genéticas Endócrinas", peso_prova: 4, frequencia_prova: 35, score: 15.5, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Endocrinologia", tema: "Tumores Endócrinos", peso_prova: 5, frequencia_prova: 40, score: 17, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Pneumologia", tema: "Doenças Pleuropulmonares Raras", peso_prova: 4, frequencia_prova: 35, score: 15.5, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Neurologia", tema: "Doenças Desmielinizantes Raras", peso_prova: 4, frequencia_prova: 35, score: 15.5, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Nefrologia", tema: "Doenças Tubulointersticiais", peso_prova: 5, frequencia_prova: 40, score: 17, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Gastroenterologia", tema: "Doenças Hepáticas Raras", peso_prova: 4, frequencia_prova: 35, score: 15.5, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Infectologia", tema: "Doenças Tropicais Raras", peso_prova: 4, frequencia_prova: 35, score: 15.5, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Hematologia", tema: "Doenças Mieloproliferativas Raras", peso_prova: 4, frequencia_prova: 35, score: 15.5, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Reumatologia", tema: "Doenças Autoimunes Raras", peso_prova: 4, frequencia_prova: 35, score: 15.5, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Psiquiatria", tema: "Transtornos Dissociativos", peso_prova: 5, frequencia_prova: 40, score: 17, prioridade: 4 },
    { area: "Cirurgia", subarea: "Cirurgia Geral", tema: "Tumores Raros do Trato Digestivo", peso_prova: 4, frequencia_prova: 35, score: 15.5, prioridade: 4 },
    { area: "Cirurgia", subarea: "Cirurgia Geral", tema: "Complicações Pós-operatórias Raras", peso_prova: 5, frequencia_prova: 40, score: 17, prioridade: 4 },
    { area: "Cirurgia", subarea: "Proctologia", tema: "Doenças Anorretais Raras", peso_prova: 4, frequencia_prova: 35, score: 15.5, prioridade: 4 },
    { area: "Cirurgia", subarea: "Urologia", tema: "Tumores Testiculares Raros", peso_prova: 4, frequencia_prova: 35, score: 15.5, prioridade: 4 },
    { area: "Cirurgia", subarea: "Vascular", tema: "Doenças Vasculares Raras", peso_prova: 4, frequencia_prova: 35, score: 15.5, prioridade: 4 },
    { area: "Pediatria", subarea: "Neonatologia", tema: "Doenças Metabólicas Neonatais Raras", peso_prova: 4, frequencia_prova: 35, score: 15.5, prioridade: 4 },
    { area: "Pediatria", subarea: "Geral", tema: "Doenças Genéticas Raras", peso_prova: 4, frequencia_prova: 35, score: 15.5, prioridade: 4 },
    { area: "Pediatria", subarea: "Geral", tema: "Erros Inatos do Metabolismo", peso_prova: 5, frequencia_prova: 40, score: 17, prioridade: 4 },
    { area: "Ginecologia e Obstetrícia", subarea: "Ginecologia", tema: "Tumores Ginecológicos Raros", peso_prova: 4, frequencia_prova: 35, score: 15.5, prioridade: 4 },
    { area: "Ginecologia e Obstetrícia", subarea: "Obstetrícia", tema: "Complicações Obstétricas Raras", peso_prova: 4, frequencia_prova: 35, score: 15.5, prioridade: 4 },
    { area: "Preventiva", subarea: "Epidemiologia", tema: "Modelos Estatísticos Avançados", peso_prova: 4, frequencia_prova: 35, score: 15.5, prioridade: 4 },
    { area: "Preventiva", subarea: "Saúde Pública", tema: "Políticas Públicas Específicas", peso_prova: 4, frequencia_prova: 35, score: 15.5, prioridade: 4 },
    { area: "Preventiva", subarea: "Saúde Pública", tema: "Sistemas Internacionais de Saúde", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Cardiologia", tema: "Doenças do Nó Sinusal", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Cardiologia", tema: "Doenças do Sistema de Condução", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Endocrinologia", tema: "Hipogonadismo", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Endocrinologia", tema: "Síndrome dos Ovários Policísticos (visão clínica)", peso_prova: 5, frequencia_prova: 40, score: 17, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Pneumologia", tema: "Doenças Restritivas Raras", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Pneumologia", tema: "Doenças da Pleura Raras", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Neurologia", tema: "Doenças do Neurônio Motor", peso_prova: 5, frequencia_prova: 40, score: 17, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Neurologia", tema: "Ataxias Hereditárias", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Nefrologia", tema: "Doenças Glomerulares Raras", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Gastroenterologia", tema: "Doenças do Intestino Delgado Raras", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Gastroenterologia", tema: "Distúrbios da Motilidade Esofágica", peso_prova: 5, frequencia_prova: 40, score: 17, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Infectologia", tema: "Infecções Fúngicas Sistêmicas Raras", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Hematologia", tema: "Doenças Hematológicas Raras", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Reumatologia", tema: "Síndromes Paraneoplásicas Reumatológicas", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Clínica Médica", subarea: "Psiquiatria", tema: "Transtornos Somatoformes", peso_prova: 5, frequencia_prova: 40, score: 17, prioridade: 4 },
    { area: "Cirurgia", subarea: "Cirurgia Geral", tema: "Tumores Neuroendócrinos Digestivos", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Cirurgia", subarea: "Cirurgia Geral", tema: "Doenças Raras do Esôfago", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Cirurgia", subarea: "Proctologia", tema: "Tumores Anorretais Raros", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Cirurgia", subarea: "Urologia", tema: "Doenças Congênitas Urológicas no Adulto", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Cirurgia", subarea: "Vascular", tema: "Vasculites Cirúrgicas Raras", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Pediatria", subarea: "Neonatologia", tema: "Síndromes Genéticas Neonatais", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Pediatria", subarea: "Geral", tema: "Doenças Autoimunes Pediátricas Raras", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Pediatria", subarea: "Geral", tema: "Doenças Endócrinas Pediátricas Raras", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Ginecologia e Obstetrícia", subarea: "Ginecologia", tema: "Síndromes Endócrinas Ginecológicas Raras", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Ginecologia e Obstetrícia", subarea: "Obstetrícia", tema: "Doenças Raras na Gestação", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Preventiva", subarea: "Epidemiologia", tema: "Métodos Avançados de Análise Epidemiológica", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Preventiva", subarea: "Saúde Pública", tema: "Gestão Avançada em Saúde Pública", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 },
    { area: "Preventiva", subarea: "Saúde Pública", tema: "Economia da Saúde", peso_prova: 4, frequencia_prova: 30, score: 14, prioridade: 4 }
];
